name: sota

on:
  pull_request:
    types: [opened, reopened]

jobs:
  sota-review:
    name: Pull request review
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run evaluation
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run examine script
      run: python examine.py
